[package]
name = "bayin-system-media"
version = "0.1.0"
edition = "2021"
build = "build.rs"
links = "bayin-system-media"

[dependencies]
tauri = { version = "2" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

bayin-playback = { path = "../../crates/bayin-playback" }

[build-dependencies]
tauri-plugin = { version = "2", features = ["build"] }
