/// i18n (slang).
///
/// Source JSON lives next to this file:
///   * `strings.i18n.json`     — base locale (English)
///   * `strings_zh-CN.i18n.json` — Simplified Chinese
///
/// The typed translations class is generated by running
///   `dart run slang`
/// from `bayin_flutter/`. The generator writes `strings.g.dart` into this
/// directory (and `AppLocale` / `Translations` / etc.). That file is checked
/// into source control — re-run the command after editing a JSON file.
///
/// Once generated, use it like:
///
/// ```dart
/// import 'package:bayin_flutter/src/i18n/strings.g.dart';
/// ...
/// Text(t.nav.songs);
/// ```
///
/// The Phase 1 scaffold only seeds `nav` and `common` keys; additional key
/// groups (player, scan, settings, about, …) land alongside their owning
/// pages in Phase 3+.
library;
